# Generated by Django 4.2.3 on 2023-09-02 18:42

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OAuthUser",
            fields=[
                ("code_verifier", models.TextField(max_length=500)),
                ("code_challenge", models.CharField(max_length=300)),
                (
                    "id",
                    models.CharField(
                        default=app.models.gen_random,
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("refresh_token", models.CharField(blank=True, max_length=100)),
                ("jwt_token", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "OAuthUser",
            },
        ),
    ]
